# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: no-commit-to-branch
    args: ["--branch", "main", "--pattern", "release/*"]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []
- repo: local
  hooks:
  - id: rustfmt
    name: rustfmt
    description: Check if all files follow the rustfmt style
    entry: cargo fmt --all -- --check --color always
    language: system
    pass_filenames: false
  - id: clippy
    name: clippy
    description: Run clippy on all files
    entry: cargo clippy --all-targets --all-features -- -D warnings
    language: system
    pass_filenames: false
