[package]
name = "spdk-sys"
version = "0.1.0"
edition = "2021"
links = "spdk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
autotools = "0.2.6"
bindgen = { version = "0.69.4", features = ["experimental"] }
cc = "1.0.95"
doxygen-rs = "0.4.2"
fs_extra = "1.3.0"
itertools = "0.12.1"
pkg-config = "0.3.27"
regex = "1.10.4"

[features]
default = []
bdev = []
bdev-malloc = ["bdev"]
bdev-module = ["bdev"]
nvmf = ["bdev"]
