[package]
name = "spdk-sys"
version = "0.1.0"
edition = "2021"
links = "spdk"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
autotools = "0.2.6"
bindgen = "0.66.0"
fs_extra = "1.3.0"
itertools = "0.11.0"
pkg-config = "0.3.27"

[dependencies]
errno = "0.3.1"
