[package]
name = "spdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-strings = "0.3.1"
errno = "0.3.1"
futures = "0.3.28"
libc = "0.2.146"
spdk-sys = { version = "0.1.0", path = "../spdk-sys" }
