[package]
name = "spdk"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
byte-strings = "0.3.1"
errno = "0.3.1"
futures = "0.3.28"
libc = "0.2.146"
spdk-macros = { version = "0.1.0", path = "../spdk-macros" }
spdk-sys = { version = "0.1.0", path = "../spdk-sys" }
static_init = "1.0.3"

[dev-dependencies]
byte-strings= "0.3.1"

[features]
default = []
bdev=[]
bdev-malloc = ["bdev", "spdk-sys/bdev-malloc"]
nvmf = ["bdev", "spdk-sys/nvmf"]

[[example]]
name = "bdev_hello_world"
required-features = ["bdev-malloc"]

[[example]]
name = "nvmf"
required-features = ["bdev-malloc", "nvmf"]
